#!/bin/bash
# File: ./scripts/activate-orchestration-architect
ORCHESTRATION_ARCHITECT_HOME="$HOME/orchestration_architect"
OPENAI_ENV_FILE_PATH="$HOME/keystore/api-keys/openai"

# Check if OPENAI_ENV_FILE_PATH exists
if [ ! -f "$OPENAI_ENV_FILE_PATH" ]; then
    echo "Error: OPENAI_ENV_FILE_PATH ('$OPENAI_ENV_FILE_PATH') does not exist."
    echo "Please add OPENAI_API_KEY and OPENAI_PROJECT_ID to the file."
    echo "Example:"
    echo "export OPENAI_API_KEY=\"your_api_key_here\""
    echo "export OPENAI_PROJECT_ID=\"your_project_id_here\""
    exit 1
fi

# Load environment variables
eval "$(cat $OPENAI_ENV_FILE_PATH)"
export OPENAI_API_KEY=$OPENAI_API_KEY
export OPENAI_PROJECT_ID=$OPENAI_PROJECT_ID 

# Add orchestration architect scripts to PATH

NEW_PATH="$ORCHESTRATION_ARCHITECT_HOME/scripts:$PATH"

if [ -d "$NEW_PATH" ] && [[ ":$PATH:" != *":$NEW_PATH:"* ]]; then
  export PATH="$NEW_PATH:$PATH"
fi

# Function to update PS1
update_ps1() {
    PS1="[OrchestrationArchitect] $PS1"
}

# Call the function to update PS1
update_ps1

