#!/bin/bash
show_help() {
  echo "Usage: ./terminal-ai-with-file [--file=<FILE_TO_INCLUDE>] [--message=<MESSAGE_TO_SEND>] [--help]"
  echo ""
  echo "Options:"
  echo "  --file=<FILE_TO_INCLUDE>               File to append to the message"
  echo "  --message=<MESSAGE_TO_SEND>            Message to include with attached file."
  echo "  --help                                 Show this help message and exit."
}

MESSAGE=""
FILE=""

while [[ "$1" == --* ]]; do
  case $1 in
    --message=*)
      MESSAGE="${1#*=}"
      shift
      ;;
    --file=*)
      FILE="${1#*=}"
      shift
      ;;
    --help)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      show_help
      exit 1
      ;;
  esac
done

source activate-terminal-ai
MESSAGE_TEMP_FILE=$(mktemp /tmp/tai.XXXXXXXX)
ATTACHED_TEMP_FILE=$(mktemp /tmp/tai.XXXXXXXX)
if [[ -n $MESSAGE ]]; then
  echo "$MESSAGE" >> $MESSAGE_TEMP_FILE
fi

if [[ -z $FILE ]]; then
  fzf-copy-files-to-clipboard
  wl-paste >> $ATTACHED_TEMP_FILE
elif [[ -f $FILE ]]; then
  cat $FILE >> $ATTACHED_TEMP_FILE
else
  echo "Invalid File"
  exit 1
fi
echo "MESSAGE"
echo "-------"
cat "$MESSAGE_TEMP_FILE"
echo ""
echo "ATTACHED CONTENT"
echo "-----------------"
cat "$ATTACHED_TEMP_FILE"
echo ""
read -p "Do you want to send? (Y/n): " choice
case "$choice" in
  [Yy]* )
    terminal-ai --input-file="$ATTACHED_TEMP_FILE" -- "$(cat $MESSAGE_TEMP_FILE)"
    exit 0
    ;;
  [Nn]* )
    echo "Exiting..."
    exit 1
    ;;
  * )
    echo "Invalid input. Exiting..."
    exit 1
    ;;
esac

