- name: Bootstrap LiveUSB
  hosts: localhost
  connection: local
  vars_files:
    - LiveUSB-OA001/vars.yml
    - LiveUSB-OA001/external_vars.yml
    - LiveUSB-OA001/bootstrap_vars.yml

  tasks:
    - name: Bootstrap system with base image
      tags:
        - bootstrap
      block:
        - name: Update Arch Linux keyring
          community.general.pacman:
            update_cache: true
            name:
              - archlinux-keyring
        - name: Initialise pacman keyring
          ansible.builtin.command: pacman-key --init
        - name: Repopulate keyring
          ansible.builtin.command: pacman-key --populate
        - name: Bootstrap base system
          ansible.builtin.command: "pacstrap -K
            {{ system_mount_path }}
            {{ bootstrap_pkgs | join(' ') }}"
    - name: Configure system
      tags:
        - misc_configuration
      vars:
        chroot_exec: "arch-chroot {{ system_mount_path }}"
        config_path: "{{ system_mount_path }}/etc"
        template_path: "{{ ansible_root }}/playbooks/LiveUSB-OA001/templates"
      block:
        - name: Generate fstab
          ansible.builtin.command: "genfstab -L {{ system_mount_path }}"
          register: genfstab_result
          changed_when: false
        - name: Create fstab with template from genfstab's output
          ansible.builtin.template:
            src: "{{ template_path }}/fstab.j2"
            dest: "{{ config_path }}/fstab"
        - name: Set Hostname
          ansible.builtin.copy:
            dest: "{{ config_path }}/hostname"
            content: "{{ bootstrap_config.hostname }}"
        - name: Set Timezone
          ansible.builtin.command:
            cmd: "{{ chroot_exec }}
              ln -sf /usr/share/zoneinfo/{{
              bootstrap_config.timezone }} /etc/localtime"
            creates: "{{ config_path }}/localtime"
        - name: Update locale generator config
          ansible.builtin.lineinfile:
            path: "{{ config_path }}/locale.gen"
            regexp: '^#{{ item }}.UTF-8 UTF-8'
            line: '{{ item }}.UTF-8 UTF-8'
          loop: "{{ bootstrap_config.installed_locales }}"
        - name: Generate Locales
          ansible.builtin.command: "{{ chroot_exec }}
            locale-gen"
        - name: Set Locale
          ansible.builtin.copy:
            dest: "{{ config_path }}/locale.conf"
            content: "LANG={{ bootstrap_config.locale }}.UTF-8"
        - name: Set default shell for root
          ansible.builtin.command: "{{ chroot_exec }}
            chsh -s {{ bootstrap_config.default_shell }}"

    - name: Configure and build initramfs
      tags: 
        - initramfs
      vars:
        chroot_exec: "arch-chroot {{ system_mount_path }}"
        initramfs_config_file: "{{ system_mount_path }}/etc/mkinitcpio.conf"
      block:
        - name: Configure initramfs hooks
          ansible.builtin.lineinfile:
            path: "{{ initramfs_config_file }}"
            regexp: '^HOOKS='
            line: "HOOKS=({{ initramfs_config.hooks | join(' ')}})"
        - name: Configure initramfs modules
          ansible.builtin.lineinfile:
            path: "{{ initramfs_config_file }}"
            regexp: '^MODULES='
            line: "MODULES=({{ initramfs_config.modules | join(' ')}})"
        - name: Recreate initramfs image
          ansible.builtin.command: '{{ chroot_exec }} mkinitcpio -P'
     
    - name: Configure bootloader (GRUB)
      tags: 
        - bootloader
      vars:
        chroot_exec: "arch-chroot {{ system_mount_path }}"
        grub_config_file: "{{ system_mount_path }}/etc/default/grub"
      block:
        - name: Configure default kernel parameters
          ansible.builtin.lineinfile:
            path: '{{ grub_config_file }}'
            search_string: 'GRUB_CMDLINE_LINUX_DEFAULT='
            line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ grub_config.default_kernel_params }}"'

        - name: Install GRUB
          args:
            creates: '{{ system_mount_path }}/boot/EFI/BOOT/BOOTX64.EFI'
          ansible.builtin.shell: "{{ chroot_exec }} grub-install {{ grub_config.grub_install_flags }}"
        - name: Generate grub.cfg
          args:
            creates: '{{ system_mount_path }}/boot/grub/grub.cfg'
          ansible.builtin.shell: "{{ chroot_exec }} grub-mkconfig -o /boot/grub/grub.cfg"


- name: Secure LiveUSB
  hosts: localhost
  connection: local
  vars_files: 
    - LiveUSB-OA001/vars.yml
    - LiveUSB-OA001/external_vars.yml
    - LiveUSB-OA001/bootstrap_vars.yml
  vars_prompt:
    - name: password
      prompt: "Password for luks and ssh key passphrase"
      private: true
  tasks:
    - name: Secure the LiveUSB
      tags:
        - security
      vars:
        chroot_exec: "arch-chroot {{ system_mount_path }}"
      block:
        - name: Set root password
          ansible.builtin.shell: "chpasswd --root {{ system_mount_path }} root:{{ password }}"

        - name: Add luks passphrase
          ansible.builtin.include_role:
            name: luks
          vars:
            state: present
            luks:
              name: '{{ item }}'
              keyfile: '{{ luks_keyfile }}'
              path: '/dev/disk/by-label/{{ item }}'
            luks_new_passphrase: '{{ password }}'
          loop:
            - OA001_Encrypted_System
            - OA001_Encrypted_Data
