grid-columns: 1
classes._in: {
  shape: circle
  label: ""
  width: 10
  style.stroke: black
  style.fill: white
}
classes._out: {
  shape: circle
  label: ""
  width: 10
  style.stroke: black
  style.fill: black
}


Tasks.Task 1: @task1.d2.label
Tasks.Task 2: @task2.d2.label

Tasks: {
  _in.class:_in;
  _out.class:_out;
  _in -- T*
  T* -- _out
}

# --------
# Expanded
# --------
# - Adds the _in and _out class for every child `T*: {_in.class: _in; _out.class: _out; _in -- T* -- _out}`
# - Connect inner diagrams
#   - `_in -- T*_in` instead of `_in -- T*` 
#   - `T*._out -- _out` instead of `T* -- _out`
#
# Tasks: {
#   _in.class:_in;
#   _out.class:_out;
#   T*: {_in.class: _in; _out.class: _out; _in -- T* -- _out}
#   _in -- T*._in
#   T*._out -- _out
# }
