# vars/specifications/0.8.0/playbooks.yml
---
playbooks_specifications:
  # Start Metadata
  metadata:
    non_collection_keys: ['Base', 'metadata']
    collections:
      Meta:
        collection_name: Meta
        path: playbooks/Meta
        template_path: playbooks/meta.yml.j2
        description: "A collection of playbooks build, modify and extend Orchestration
          Architect, ensuring that the design of the system is consistent, managable,
          adheres to the underlying design principles and ensures compatability with
          different components and dynamically updating the interactions between components
          when designs change. Manages specifications, migrations, playbooks and roles."
      OA001_Provision_LiveUSB:
        collection_name: OA001_Provision_LiveUSB
        path: playbooks/OA001_Provision_LiveUSB
        files:
          - playbooks/OA001_Provision_LiveUSB/vars.yml
        description: "A collection of playbooks to build the portable management node
          of Orchestration Architect. Depends only on ansible and pacman as its dependency.
          If USB not available use a loop device. This collection can provision a LiveUSB
          environment with full disk encryption and persistence, open and mount LiveUSB,
          customize, modify and recover existing installations, and safely prepare device
          for ejection.
          Also allows for rekeying luks and root accounts (requires specification
          of a development luks keyfile or entering luks passphrase). Tested under default
          Arch Linux Installation Live Install media."
      OA001_LiveUSB:
        collection_name: OA001_LiveUSB
        description: "Contains playbooks to configure startup operations, customize
          the system, create snapshots and remote backups. Update subvolume or bind
          mounts, add/remove service accounts. It also includes the generation of the
          image fora live operating system of OA002_Hypervisor and deployment over PXE,
          which has a default auto login guest account, desktop environment, with baked
          SSH access for the OA001 root user and OA001_service worker, to allow instant
          access to deployed system."
        path: playbooks/OA001_LiveUSB
      OA002_Hypervisor:
        collection_name: OA002_Hypervisor
        path: playbooks/OA002_Hypervisor
        description: "Playbooks to remotely manage a bare metal nested hypervisor. Allows
          for instant reconfiguration from fresh boot of the live environment booted
          from the PXE service, and configuration of a running system that is persisted
          due to configuration running from playbook. Connects via SSH using credentials
          baked in."
      Default:
        collection_name: Default
        description: Playbooks not in a collection.
        path: playbooks/Default
  Base:
    playbook_vars_files:
      - ../../vars/environment.yml
    sections:
      - file_header
      - 30_managed_block_before_content
      - 50_content_region_message
      - 90_managed_block_after_content
  Meta:
    Setup_Environment:
      playbook_name: Setup Environment
      playbook_path: Setup_Environment.yml
      playbook_description: Ensures environment variables file exists and populated correctly
      state: updated

    Execute_Orchestrator:
      state: pristine
      playbook_name: Execute Meta Orchestrator to Process All Specifications
      playbook_path: Execute_Orchestrator.yml
      metadata:
        pre_run_playbooks:
          - Setup_Environment.yml
      plays:
        - play_id: Execute Orchestrator
          trigger_role:
            name: meta_orchestrator
            state: present
            specifications_version: "0.8.0"
            specifications_path: "vars/specifications/0.8.0"

