# file: roles/luks/tasks/info.yml
# role: luks
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK auto_includes
- name: Include task info.pre.yml
  ansible.builtin.include_tasks: "info.pre.yml"
# END ORCHESTRATION ARCHITECT MANAGED BLOCK auto_includes
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Print out provided parameters
  ansible.builtin.debug:
    msg: "{{ luks_params }}"

# Checking the status of the LUKS volume
- name: Gather LUKS volume status information
  ansible.builtin.command: cryptsetup status {{ luks_params.mapped_name }}
  changed_when: false
  register: luks_status
  ignore_errors: true
  become: true
  when: luks_params.mapped_name!=omit

# Displaying the status of the LUKS volume
- name: Display LUKS volume status
  ansible.builtin.debug:
    msg: >-
      {{ luks_status.stdout }}
  when: luks_status is defined and luks_status.rc == 0

# Handling the case where the LUKS volume is not found or other errors
- name: Display error message if LUKS volume status check fails
  ansible.builtin.debug:
    msg: "Failed to check LUKS volume status or volume does not exist."
  when: luks_status is defined and luks_status.rc != 0

### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
