[book]
authors = ["Andrew Briscoe"]
language = "en"
multilingual = false
src = "src"
title = "Orchestration Architect: The Architecture Book"

[preprocessor.cmdrun]

[preprocessor.d2]
path = "d2"
layout = "elk"
inline = true
