# file: roles/loop_device/tasks/inactive.yml
# role: loop_device
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Ensure Loop Device Target Available
  vars:
    loop_device_target: "{{ 'target' | extract(loop_device_params) }}"
  block:
    - name: Remove 'Loop Device Alias' for 'Loop Device Target'
      vars:
        loop_device_map_name: "{{ 'map_name' | extract(loop_device_params) }}"
        loop_device_target: "{{ 'target' | extract(loop_device_params) }}"
      block:
        - name: Remove Loop Device Alias in Device Map
          ansible.builtin.command: dmsetup delete {{ loop_device_map_name }}
          deletes: /dev/mapper/{{ loop_device_map_name }}

        - name: Find Loop Device By Target
          vars:
            loop_device_target: "{{ 'target' | extract(loop_device_params) }}"
          ansible.builtin.command: "losetup -j {{ loop_device_target }}"
          changed_when: false
          register: loop_device_find

        - name: Remove Attached Loop Device
          when: "loop_device_find.stdout != ''"
          vars:
            found_loop_device: >-
              {{
                loop_device_find.stdout
                | regex_search(
                    '(/dev/loop[0-9]+)',
                    '\1'
                    )
               }}
          ansible.builtin.command: "losetup -d {{ found_loop_device }}"
          changed_when: true

### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
