# file: roles/loop_device/tasks/present.yml
# role: loop_device
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Ensure Loop Device Target Directory Exists
  ansible.builtin.file:
    state: directory
    mode: "{{ directory_mode | default('0700') }}"
    path: "{{ 'target' | extract(loop_device_params) | dirname }}"

- name: Ensure Loop Device Target Exists
  community.general.filesize:
    path: "{{ 'target' | extract(loop_device_params) }}"
    size: "{{ 'size' | extract(loop_device_params) | default(omit, true) }}"

- name: Create Loop Device to Access File as Storage Device
  ansible.builtin.command: "losetup --find --nooverlap --show {{ 'target' | extract(loop_device_params) }}"
  changed_when: "'loop' in loop_device_result.stdout"
  register: loop_device_result

- name: Map Predictable Device Name to Loop Device
  block:
    - name: Get loop device sectors count
      ansible.builtin.command: "blockdev --getsz {{ loop_device_result.stdout }}"
      register: loop_device_sectors_result
      changed_when: false

    - name: Create Loop Device Alias in Device Map
      ansible.builtin.shell: >-
        set -o pipefail &&
        echo "0 {{ loop_device_sectors_result.stdout }}
        linear {{ loop_device_result.stdout }} 0" |
        dmsetup create {{ 'map_name' | extract(loop_device_params) }}
      args:
        creates: /dev/mapper/{{ 'map_name' | extract(loop_device_params) }}

### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
