# file: roles/mount/tasks/present.yml
# role: mount
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Nested Mount(BTRFS subvolumes)
  when:
    - "'map' in mount_params and mount_params.map!=omit"
    - "'type' in mount_params and mount_params.type=='btrfs'"
  block:
    - name: Mount BTRFS Subvolumes
      loop: "{{ mount.map }}"
      loop_control:
        loop_var: sub_mount
      ansible.posix.mount:
        state: mounted
        fstype: "{{ mount.type }}"
        src: "{{ mount.source }}"
        opts: "{{ sub_mount.source }}"
        path: "{{ sub_mount.target }}"
        fstab: "{{ mount.fstab | default(omit) }}"
      when: sub_mount.options is not defined

- name: Mount Filesystems
  ansible.posix.mount:
    state: mounted
    fstype: "{{ mount.type }}"
    src: "{{ mount.source }}"
    opts: "{{ mount.options | default(omit) }}"
    path: "{{ mount.target }}"
    fstab: "{{ mount.fstab | default(omit) }}"
  when:
    - mount.target is defined
    - mount.type!='bind'
    - mount.type!='tmpfs'

- name: Bind source to Target
  ansible.posix.mount:
    state: mounted
    fstype: none
    opts: bind
    src: "{{ mount.source }}"
    path: "{{ mount.target }}"
    fstab: "{{ mount.fstab | default(omit) }}"
  when: mount.type=='bind'

- name: Add TmpFS Mount Fstab entries
  ansible.posix.mount:
    state: mounted
    fstype: "{{ mount.type }}"
    opts: "{{ mount.options }}"
    src: "{{ mount.type }}"
    path: "{{ mount.target }}"
    fstab: "{{ mount.fstab | default(omit) }}"
  when: mount.type=='tmpfs'

### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
