#!/bin/sh

LOCAL_WORKSPACE="$HOME/repos/orchestration-architect"
USER_REPO="$HOME/repos/orchestration-architect.git"

while IFS=' ' read -r branch ref; do
  cd "$USER_REPO" || exit
  git worktree add "$LOCAL_WORKSPACE/$branch" "$ref"
done

