OA999_applications:
  system_default_pkgs:
    - amd-ucode
    - ansible
    - base
    - bat
    - btop
    - btrfs-progs
    - cryptsetup
    - dhcpcd
    - dosfstools
    - e2fsprogs
    - exfatprogs
    - fzf
    - git
    - grub
    - intel-ucode
    - kernel-modules-hook
    - linux
    - linux-firmware
    - lynx
    - man-db
    - man-pages
    - most
    - neovim
    - ntfs-3g
    - openssh
    - openvswitch
    - parted
    - python
    - ripgrep
    - rsync
    - sudo
    - firefox
    - sway
    - texinfo
    - tmux
    - tree
    - wget
    - wpa_supplicant
    - zsh
