Architecture: {
  Self-Assembly
  Self-Updating
  Self-Modification
  Self-Verification
  Self-Documenting
  Self-Versioning
}

Software Engeering Domains: {
  ARCHITECTURE;
  REQUIREMENTS: {
    ELICITATION;
    ANALYSIS
  }
  DESIGNS: {
    
  }
  DEVELOPMENT;
  CONFIGURATION MANAGEMENT;
  PROCESS MANAGEMENT;


}
