PRESENT SITUATION: {
    NOW -> Kanban.TASK: Add Task 
    Kanban.TASK -> DOCS: Complete Task 

    Kanban: {  
    TASK: MOVE TO
    }

    NOW: {
        Daily Notes.Requirements for Software Engineering Process 
    } 
    DOCS: {
        OA_PROJECT Sandbox."REQUIREMENT-000 Development Model.draft.md"
    }

    NOW.Daily Notes.Requirements for Software Engineering Process -> DOCS.OA_PROJECT Sandbox."REQUIREMENT-000 Development Model.draft.md": moved to
}

POTENTIAL FUTURE SITUATION: {    
    NOW.Daily Notes: {grid-columns: 2;PROBLEM; GOAL;
    #PROBLEM -> NEED <- GOAL
    }
    NOW.Daily Notes -> Trigger REQUIREMENT Doc Development: is provided
    # NOW.Daily Notes.PROBLEM -> Trigger REQUIREMENT Doc Development: is provided
    #NOW.Daily Notes -> Sandbox.OA_PROJECT: trigger Inception Command
    Trigger REQUIREMENT Doc Development -> Sandbox.OA_PROJECT: is supplied context
    # Frees up sandbox clutter and provides a location within the docs 
    # namespace for linking historic documents 
    Sandbox.OA_PROJECT -> DOCS.NOTES: is archived to
    Archive Notes Function -> DOCS.NOTES: is a producer
    Complete Task -> Archive Notes Function: is triggered
    Sandbox.OA_PROJECT.Requirements Draft -> Archive Notes Function: is a consumer of
    Archive Notes Function -> DOCS.REQUIREMENTS: is a provider for
    DOCS.REQUIREMENTS.REQUIREMENT DOC -> DOCS.NOTES.HISTORIC ARCHIVE DOC: is the latest 
    Kanban.TASK -> Sandbox.OA_PROJECT: is an activity to identify elicited needs to analyse the requirements

    
    #Sandbox.OA_PROJECT.Requirements -> OA_NOTE.Requirements.V1: is archived
    #Sandbox.OA_PROJECT.Requirements Draft -> Sandbox.OA_PROJECT.Requirements Draft: is symlink target
    Trigger REQUIREMENT Doc Development -> Kanban.TASK: is generated by
    
    
    #NOW.Daily Notes.PROBLEM -> Kanban.TASK.REQ Elicitation: ADD ELICITATION SUBTASK
    #NOW.Daily Notes.PROBLEM -> Kanban.TASK.REQ Analysis: ADD ANALYSIS SUBTASK 
    Kanban.TASK: {label: TASK}
    Kanban.TASK.Start: {label: REQ Inception} 
    Kanban.TASK.Start -> Kanban.TASK.REQ Elicitation: is supplied problems and goals 
    Kanban.TASK -> Complete Task
    Kanban.TASK.REQ Elicitation -> Kanban.TASK.REQ Analysis: is a dependent prequiste
    # Kanban.TASK.REQ Elicitation -> Sandbox.OA_PROJECT.Requirements Draft: is added to 
    # Kanban.TASK.REQ Analysis -> Sandbox.OA_PROJECT.Requirements Draft: is added to
    Complete Task -> DOCS.REQUIREMENTS.REQUIREMENT DOC: is outcome 
    #   Trigger REQUIREMENT Doc Development -> DOCS.REQUIREMENTS.REQUIREMENT DOC DRAFT SYMLINK: is created by
    #   DOCS.NOTES.Requirements Draft -> DOCS.REQUIREMENTS.REQUIREMENT DOC DRAFT SYMLINK: is a resource
    #   Complete Task -> DOCS.REQUIREMENTS.REQUIREMENT DOC DRAFT SYMLINK: removes

 
    

    #DOCS.REQUIREMENTS.REQUIREMENT DOC
    # NOW.Daily Notes.PROBLEM -> Sandbox.OA_PROJECT.Requirements Draft: Start Requirements Process 

}
