# file: roles/storage/tasks/mounted.yml
# role: storage
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

# (@functor) Storage(_ -> Opened) -> LUKS(_ -> Opened)
- name: Map Storage to Opened State
  ansible.builtin.include_role:
    name: storage
  vars:
    storage_state: opened

- name: Map BTRFS Subvolumes to Present State (if required)
  when:
    - "'btrfs_subvolumes' in storage_params"
    - "storage_params.btrfs_subvolumes != omit"
  ansible.builtin.include_role:
    name: btrfs_subvolumes
  vars:
    btrfs_subvolumes: "{{ 'btrfs_subvolumes' | extract(storage_params) }}"
    btrfs_subvolumes_state: present

# (@functor) Storage(Opened -> Mounted) -> Mount(_ -> Present)
- name: Map Mount Table Entries to Mounted State
  when: "storage_params.mount_table!=omit"
  vars:
    mount_table: "{{ 'mount_table' | extract(storage_params) }}"
  block:
    # Note: Added condition in loop because jinja2 is still evaluated causing loop
    #   parameter to be invalid. Since the when clause is distributed to the block tasks.
    #
    #   In the future, the functors will be generated in a separate task, and
    #   this hack will not be needed.
    - name: Mount Table Entry
      loop: "{{ [] if mount_table == omit else mount_table }}"
      loop_control:
        loop_var: mount
      ansible.builtin.include_role:
        name: mount
      vars:
        mount_state: mounted

### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
