# file: roles/storage/tasks/opened.yml
# role: storage
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
- name: Ensure Storage is Present
  ansible.builtin.include_tasks: present.yml
- name: Attach Loop Device (if required)
  when: "'loop_device' in storage_params and storage_params.loop_device!=omit"
  ansible.builtin.include_role:
    name: loop_device
  vars:
    loop_device_state: active
      
  loop:
    - "{{ 'loop_device' | extract(storage_params)}}"
  loop_control:
    loop_var: loop_device

- name: Map LUKS to Unlocked state (if required)
  when: "'luks' in storage_params and storage_params.luks!=omit"
  ansible.builtin.include_role:
    name: luks
  vars:
    luks: "{{ 'luks' | extract(storage_params) }}"
    luks_state: opened


### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
