# file: roles/storage/tasks/unmounted.yml
# role: storage
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Unmount Entries in Mount Table
  when: "'mount_table' in storage_params and storage_params.mount_table!=omit"
  vars:
    mount_state: unmounted
    mount_table: "{{ 'mount_table' | extract(storage_params) }}"
  ansible.builtin.include_role:
    name: mount
  loop: "{{ ([] if mount_table == omit else mount_table) | reverse }}"
  loop_control:
    loop_var: mount

### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
