
# playbook: Setup Environment
# file: playbooks/Meta/Setup_Environment.yml
# version: 0.8.0
---
# (@TODO=OA-0.8.1-ALIGN_PATH_TRANSFORMATIONS): Add args based loop, and use it to set the temporary directory
# (@TODO-OA-0.8.1-ALIGN_PATH_TRANSFORMATIONS): Change Work Directories to use Temp_Files
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK pre_run_playbooks 
# END ORCHESTRATION ARCHITECT MANAGED BLOCK pre_run_playbooks 
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Configure the Environment
  connection: local
  hosts: localhost
  vars:
    environment_vars_file_path: "../../vars/environment.yml"
  tasks:
    - name: Ensure environment variable directory exists
      ansible.builtin.file:
        state: directory
        path: "{{ environment_vars_file_path | dirname }}"
        mode: "0770"
    - name: Write base path to environment variables file
      vars:
        base_path: "{{ playbook_dir | dirname | realpath | dirname }}"
      ansible.builtin.lineinfile:
        path: "{{ environment_vars_file_path }}"
        line: "base_path: {{ base_path }}"
        create: true
    - name: Include Environment Variables File
      ansible.builtin.include_vars:
        file: "{{ environment_vars_file_path }}"
    - name: Displayed Included Variables
      ansible.builtin.debug:
        msg: |
          base_path: {{ base_path }}
### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content

