# file: roles/qemu_runtime/tasks/absent.yml
# role: qemu_runtime
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
- name: Stop the systemd-nspawn container
  ansible.builtin.command: "kill $(cat /run/nspawn_{{ nspawn_runner_params.machine_name }}.pid)"
  failed_when: result.rc not in [0, 1]  # Task fails unless the result code is 0 (successful kill) or 1 (process not running)
  changed_when: result.rc == 0  # Only report a change if the kill command was successful

- name: Remove the nspawn PID file
  ansible.builtin.file:
    path: "/run/nspawn_{{ nspawn_runner_params.machine_name }}.pid"
    state: absent
  changed_when: false  # No change if the file is already absent
### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
