# file: roles/qemu_runtime/tasks/present.yml
# role: qemu_runtime
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
- name: Ensure the KVM script for QEMU is created
  ansible.builtin.template:
    src: "kvm.j2"
    dest: "/run/qemu_{{ qemu_runtime_params.machine_name }}"
    mode: '0700'
  vars:
    template_variables:
      device_path: "{{ qemu_runtime_params.device_path }}"
      memory: "{{ qemu_runtime_params.memory }}"
      cpu_cores: "{{ qemu_runtime_params.cpu_cores }}"
      sockets: "{{ qemu_runtime_params.sockets }}"
      smp: "{{ qemu_runtime_params.smp }}"
      vga: "{{ qemu_runtime_params.vga }}"
      spice_socket: "{{ qemu_runtime_params.spice_socket }}"
      port_forwarding: "{{ (qemu_runtime_params.port_forwarding is defined and qemu_runtime_params != omit) | ternary(qemu_runtime_params.port_forwarding, '') }}"
      extras: "{{ (qemu_runtime_params.extras is defined and qemu_runtime_params.extras != omit) | ternary(qemu_runtime_params.extras, '')  }}"
      machine_name: "{{ qemu_runtime_params.machine_name | default('machine') }}"

- name: Run the QEMU VM
  ansible.builtin.command: "/run/qemu_{{ qemu_runtime_params.machine_name }}"
  async: 60
  poll: 0
  args:
    creates: "/run/qemu_{{ qemu_runtime_params.machine_name }}.pid"  # Only create if the file doesn't already exist
### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
