# file: roles/nspawn/tasks/info.yml
# role: nspawn
# version: 0.8.1
---
### 02_Managed_Region_Before_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content
# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK auto_includes
- name: Include task info.pre.yml
  ansible.builtin.include_tasks: "info.pre.yml"
# END ORCHESTRATION ARCHITECT MANAGED BLOCK auto_includes
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 30_managed_block_before_content

### 03_Content_Region ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message
# NOTE: Manual changes should occur in this region, below the managed block
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 50_content_region_message

- name: Show Template
  vars:
    template_variables: 
      machine_name: "{{ 'machine_name' | extract(nspawn_params) }}"
      target: "{{ 'target' | extract(nspawn_params) }}"
  block:
    - name: Show Rendered Command
      vars:
        nspawn_command: "{{ lookup('ansible.builtin.template', 'command_template' | extract(nspawn_params)) }}"
      ansible.builtin.debug:
        msg: "{{ nspawn_command }}"
### 04_Managed_Region_After_Content ORCHESTRATION ARCHITECT REGION ###

# BEGIN ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
# END ORCHESTRATION ARCHITECT MANAGED BLOCK 90_managed_block_after_content
